name: .NET build which creates nuget package with IDEA StatiCa project templates

on:
  push:
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.0.x'
  package_version: 1.0.${{ github.run_number }}

jobs:
  BuildAndTest:
    name: "Build and Test IOM"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: .NET project version updater
      uses: vers-one/dotnet-project-version-updater@v1.3
      with:
        file: src/MPospisil.Dotnet.Templates.csproj
        version: ${{ env.package_version }}           

    - name: Install dependencies
      run: dotnet restore src/MPospisil.Dotnet.Templates.csproj

    - name: Build IdeaStatiCa.Dotnet.Templates.csproj
      run: dotnet build src/MPospisil.Dotnet.Templates.csproj --configuration Release

    - name: Pack MPospisil.Dotnet.Templates.csproj
      run: dotnet pack src/MPospisil.Dotnet.Templates.csproj --configuration Release -o src/nuget --no-restore

    - uses: actions/upload-artifact@v4
      with:
        name: MPospisil.Dotnet.Templates
        path: src/nuget/*.nupkg     

